[features]
seeds = false
skip-lint = false
[programs.localnet]
market_contracts = "HQZV1Ukjs5bJGaZjZoijVyK1HBBqzwsZX9eAwmkvTG4u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jimii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
